alias ujb='jspm unbundle'
alias jd='jspm depcache'
alias comp='gulp comp -p'
alias ogc='open -a Google\ Chrome --args --disable-web-security --allow-file-access-from-files'
alias alog='tail -f /usr/local/var/log/nginx/access.log'
alias elog='tail -f /usr/local/var/log/nginx/error.log'
