export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
export PYTHONASYNCIODEBUG=1
# export PIPENV_DEFAULT_PYTHON_VERSION=3.6
# export PIPENV_MAX_DEPTH=1
# export PIPENV_IGNORE_VIRTUALENVS=1
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
